### PR TITLE
[WIP] First pass at fish shell support

### PR DESCRIPTION
**Pull request by scalvert**
Adding fish shell support to notion (#152)

TODO:

- [x] Adding a backend (fish.rs) to crates/notion-core/src/shell/, with a type Fish that implements Shell
- [ ] Adding a bootup script (notion.fish) to shell/unix/, with a wrapper function notion to get installed at console boot time
- [ ] Edit install.sh.in to include installing notion.fish to ~/.config/fish/functions

### CODE REVIEW

**Comment by scalvert** [comment]
@dherman any tips on tests for this?

**Comment by dherman** [comment]
@scalvert Good question -- @mikrostew may have thoughts on this.

This is super exciting—thanks for working on it!

**Comment by dherman** [comment]
@scalvert Also, a heads up, I'm thinking about refactoring the directory layout so that we don't clutter the `.notion` directory with scripts for every shell we support. I'll comment with a link to the issue when it's filed. But don't let that block you here. That'll just be a minor refactor.

**Comment by scalvert** [comment]
Sounds good. I'm happy to move whenever.

**Comment by dherman** [comment]
@scalvert I filed issue #177 for the `shell` directory (and #179 is a sort of unified view of the updated directory layout). It's not implemented yet and I probably won't tackle it until after I finish #148 so it may not end up affecting this PR.

**Comment by scalvert** [comment]
okie dokie

**Comment by stefanpenner** [comment]
until this lands a quick hack to use notion:


```fish
set -g fish_user_paths  $HOME/.notion/bin $fish_user_paths

function notion
 $HOME/.notion/notion $argv
end
```

**Pull request closed without merging**
